name: auto-testing
on: [push]
jobs:
  run:
    runs-on: [ubuntu-20.04]
    container: docker://churnwebapp/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: sanity-check
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python test.py
